# Generated by Django 4.2.4 on 2023-08-15 14:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_remove_record_address_remove_record_city_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_info',
            new_name='Userinfo',
        ),
    ]
