# Generated by Django 4.2.4 on 2023-08-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_info_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='path',
            field=models.FilePathField(path='../static'),
        ),
    ]
